#!/bin/bash

source /usr/share/yunohost/helpers

# Stop and remove the docker container
ynh_script_progression "Stopping and removing the docker container..."
docker stop hello-docker-ynh
docker rm hello-docker-ynh

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx web server configuration..."
ynh_config_remove_nginx
